server:
  port: 8001
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
mybatis-plus:
  mapper-locations: classpath:/com/potoyang/learn/blog/*/mapper/*Mapper.xml
  type-aliases-package: com.potoyang.learn.blog.*.model
  global-config:
    db-config:
      id-type: auto
    refresh: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: "blogApplication"
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 192.168.101.201:22122
  web-server-url: 192.168.101.201/