server:
  port: 8888
  servlet:
    session:
      timeout: 2520000
spring:
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    cache: false
  redis:
    host: 192.168.20.150
    database: 0
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: 60
        max-idle: 8
        min-idle: 0
logging:
  level:
    org.springframework: info
security:
  oauth2:
    client:
      client-id: test
      client-secret: test